
name: Deploy documentation to gh-pages

on:
  push:
    branches: [ master ]

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare directories
        run: |
          mkdir -p src/
          mkdir -p build/
      - name: Checkout remote head
        uses: actions/checkout@master
        with:
          path: src/
      - name: Install packages
        run : sudo apt-get install graphviz texlive-bibtex-extra doxygen
      - name: Configure Doc
        run: |
          cd build/
          cmake ../src/ -DCMAKE_EXECUTE_PROCESS_COMMAND_ECHO=STDOUT -DPONCA_CONFIGURE_EXAMPLES=OFF -DPONCA_CONFIGURE_TESTS=OFF
      - name: Build doc
        run: |
          cd build/
          cmake --build . --target ponca-doc
      - name: Deploy Doc
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          publish_dir: 'build/doc/html'
